### ISSUE TITLE
Codehints for array keys

### ISSUE THREAD

**Issue by TomMalbran** [Brackets-PHP/Brackets-PHP-SmartHints#6]
This was discussed in https://groups.google.com/forum/#!topic/brackets-dev/cQ6DLvAntDw.

The idea is to try and give hints for the array keys. If I have `$_POST["|"]` we could get hints for possible array keys. These keys could be obtained from the code. If around the code I have `$_POST["name"]` or `$_POST["email"]`, when I write `$_POST["|"]` i could get hints like `"name"``or`"email"`. Same can be done with other arrays.

Right now I am not sure if this is a great idea, since $_POST can change its content between runs, and if I have a variable called `$data` which could easily map to `$_POST` in a function and be a completely different array in another, I could end up with lot of usefulness hints. So maybe we could discuss it a bit before any work is done.

**Comment by winfr34k** [comment]
I would love it - Runtime changes or not, it'll save your coding time, I'm sure.

**Comment by sbcjr** [comment]
Hope this isn't dead...I love this plugin and am dying to see some of the features mentioned here and in the upcoming phases!
